### ISSUE TITLE
[feature] Add custom selectors

### ISSUE THREAD

**Issue by equinusocio** [postcss/postcss-dark-theme-class#3]
Hi! It would be awesome having a way to set custom selectors instead of only classes. For example, i want to use a single attribute (to get it with `Element.dataset.theme`) and switching its value based on the theme, something like this:

`<html data-theme="dark">...</html>`

An improved configuration would help doing this, by defining the selector type and the values:

```js
require('postcss-dark-theme-class')({
      selector: "attribute",
      darkValue: "dark",
      lightValue: "light"
})
```

This could generate `<html data-theme="dark | light" >...</html>`. 

Using this configuration:

```js
require('postcss-dark-theme-class')({
      selector: "class",
      darkValue: "is-dark",
      lightValue: "is-light"
})
```

could behave like now `<html class="is-dark | is-light" >...</html>`

**Comment by ai** [comment]
What do you think about replacing `darkClass: 'is-dark'` to `darkSelector: '.is-dark'`. The new option will allow setting `[data-theme=dark]`.

If it fits, can you send PR? Throw an error `Update darkClass: 'is-dark' to darkSelector: '.is-dark'` on old option.

**Comment by equinusocio** [comment]
By this way, we can set to use eg. a class for dark, and an attribute for light. Right now the selector type is the same for both themes. Is this correct?

**Comment by ai** [comment]
> By this way, we can set to use eg. a class for dark, and an attribute for light. Right now the selector type is the same for both themes. Is this correct?

In my suggestion there will be a way:

```js
require('postcss-dark-theme-class')({
    darkSelector: '.is-dark',
    lightSelector: '[data-mode=light]'
})
```

**Comment by equinusocio** [comment]
ok, I can try, but I'm not a javascript developer so I have to learn a bit.
