### ISSUE TITLE
Discussion: Pros and Cons of Using :where() in Modern CSS with Compatibility Concerns

### ISSUE THREAD

**Issue by bosens-China** [postcss/postcss-dark-theme-class#37]
## **Background**
The CSS `:where()` pseudo-class is a powerful tool for managing specificity by ensuring a selector’s weight is always zero. This makes it especially useful for complex selectors in large-scale projects where managing specificity can be challenging. Here's an example of its usage:

```css
:where(html.is-dark) #app {
    color: white;
}
```

However, I have concerns about its compatibility with older browsers. While `:where()` is supported in most modern browsers (e.g., Chrome 88+, Firefox 78+, Safari 15+), it is not supported in older ones like IE or outdated mobile browsers.

**Comment by ai** [comment]
Yes, we are using `where()` to have the same weight before and after transformation.

I think sorting IE is very rare request. If you really need it, you can set `useWhere: false`.
